### ISSUE TITLE
missing osx file?

### ISSUE THREAD

**Issue by r-lyeh-archived** [Themaister/SimpleGL#1]
Hey,

Did you forget to commit it? :)

**Comment by Themaister** [comment]
This project hasn't been active for 3 years :p
I think it uses SDL on OSX, but don't think I tested it. Never owned an Apple machine.

**Comment by Themaister** [comment]
There isn't even a Makefile here, so not sure what has happened, I wouldn't recommend anyone using this library for anything, really.

**Comment by r-lyeh-archived** [comment]
ok thx :)
